Added Docker Dev Container
Pitt-RAS/SUAS pull request #2
Opened 2020-01-17 02:07 UTC by xinkecf35

This commit adds come docker development stuff, namely adds a development container based off the official osrf/ros-melodic-desktop image for development use. This container is capable of running most ROS CLI tools along with Docker in Docker capability.

Still needs work on forwarding the X11 socket/relevant systems for Gazebo to work.

2020-01-17 18:29 UTC, ctrlaltf2 requested changes
Dev container works, however, there was some planning code added by https://github.com/Pitt-RAS/SUAS/pull/2/commits/7024bfdd84df5bc7541e40563faf15cc1984e760 that got left in, probably should delete this but leaving it in and merging to master shouldn't hurt (just would have a commit with extraneous changes).

2020-01-17 18:56 UTC, xinkecf35 commented
@ctrlaltf2 No, it's probably for the best, for the time being I just removed the include directory with the related header files.

2020-01-18 02:01 UTC, xinkecf35 reviewed
Acknowledging desired changes, refer to newest comment

https://github.com/Pitt-RAS/SUAS/pull/2#issuecomment-575751671

2020-01-18 05:15 UTC, ctrlaltf2 approved these changes

2020-01-18 05:16 UTC, merged